---
- name: stop vmmaster service
  service: name={{app_name}} state=stopped enabled=no
  failed_when: "vmmaster_status | failed and 'service not found' not in vmmaster_status.msg"
  register: vmmaster_status

- name: install postgres
  include: ../../install_postgres/tasks/main.yml
  when: use_postgres and not update

- name: create dir for instances
  file: path={{app_path}} state=directory mode=0755 owner={{deploy_user}} group={{deploy_user}} recurse=yes

- name: delete old directory
  file: path={{app_path}} state=absent

- name: git checkout repo
  git: repo=https://github.com/2gis/vmmaster.git dest={{app_path}} version={{vmmaster_version}} depth=1

- name: install tox
  pip: name=tox
  sudo: yes

- name: create virtualenv with deps
  shell: "cd {{app_path}} && tox"

- name: apply special config.py in vmmaster directory
  template: src={{vmmaster_config_name}} dest={{app_path}}/config.py mode=0644
  when: vmmaster_config_name != "" and change_vmmaster_config

- name: vmmaster initialize
  shell: "cd {{app_path}} && .tox/bin/python manage.py init"

- name: create log dir for instances
  file: path={{app_path}}/logs state=directory mode=0755 owner={{deploy_user}} group={{deploy_user}} recurse=yes

- name: vmmaster run migrations
  shell: "cd {{app_path}} && .tox/bin/python manage.py migrations"
  sudo: yes
  when: not update

- name: change permitions for files
  file: path={{app_path}} state=directory mode=0755 owner=vmmaster group=libvirtd recurse=yes

- name: install upstart script
  template: src=upstart.conf dest=/etc/init/{{app_name}}.conf mode=0644

- name: change permitions for files
  file: path={{app_path}} state=directory mode=0755 owner=vmmaster group=libvirtd recurse=yes

- name: start vmmaster service
  service: name={{app_name}} state=started
  failed_when: "vmmaster_status | failed and 'service not found' not in vmmaster_status.msg"
  register: vmmaster_status
