sudo: true
language: python
python:
  - 3.5.1
install:
  - pip install codecov==1.6.3
before_script:
  - ./git-hooks/run-10-flake8.sh
script:
  - make test
after_success:
  - coverage xml
  - codecov
