sudo: true
language: python
python:
  - 2.7
install:
  - ./install-dependencies.sh
  - pip install tox==1.8.1 codecov==1.6.3
  - tox -e basetest
before_script:
  - ./git-hooks/run-10-flake8.sh
script:
  - tox -e unit-with-coverage
after_success:
  - coverage xml
  - codecov
