sudo: true
language: python
python:
  - 3.5
install:
  - pip install codecov==2.0.5
# fix path for flake8 in git-hooks/run-10-flake8.sh
#before_script:
#  - make lint
script:
  - make ctest
after_success:
  - coverage xml
  - codecov
