codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "0...50"
  status:
    project:
      default:
        target: auto
        threshold: 5%
        base: parent
    patch: no
    changes: no

