---
- name: stop vmmaster service
  service: name={{app_name}} state=stopped enabled=no
  failed_when: "vmmaster_status | failed and 'service not found' not in vmmaster_status.msg"
  register: vmmaster_status

- name: install postgres
  include: ../../postgres/tasks/main.yml
  when: use_postgres and not update

- name: delete old directory
  file: path={{app_path}} state=absent

- name: create dir for instances
  file: path={{app_path}} state=directory mode=0755 owner={{deploy_user}} group={{deploy_user}} recurse=yes

- name: git checkout repo
  git: repo=https://github.com/2gis/vmmaster.git dest={{app_path}} version={{vmmaster_version}}
  sudo: no

- name: install dependencies
  shell: chmod +x {{app_path}}/install-dependencies.sh && {{app_path}}/install-dependencies.sh

- name: install tox
  pip: name=tox
  sudo: yes

- name: create virtualenv with deps
  shell: "cd {{app_path}} && tox"
  sudo: no

- name: apply special config.py in vmmaster directory
  template: src={{vmmaster_config_name}} dest={{app_path}}/config.py mode=0644
  when: vmmaster_config_name != "" and change_vmmaster_config

- name: vmmaster initialize
  shell: "cd {{app_path}} && .tox/bin/python manage.py init"

- name: create log dir for instances
  file: path={{app_path}}/logs state=directory mode=0755 owner={{deploy_user}} group={{deploy_user}} recurse=yes

- name: vmmaster run migrations
  shell: "cd {{app_path}} && .tox/bin/python manage.py migrations"
  sudo: yes
  when: not update

- name: change permitions for files
  file: path={{app_path}} state=directory mode=0755 owner=vmmaster group=libvirtd recurse=yes

- name: install upstart vmmaster script
  template: src=upstart_vmmaster.conf dest=/etc/init/{{app_name}}.conf mode=0644

- name: start vmmaster service
  service: name={{app_name}} state=started
  failed_when: "vmmaster_status | failed and 'service not found' not in vmmaster_status.msg"
