---
- name: stop vmpool service
  service: name={{vmpool_name}} state=stopped enabled=no
  failed_when: "vmpool_status | failed and 'service not found' not in vmpool_status.msg"
  register: vmpool_status

- name: install postgres
  include: ../../postgres/tasks/main.yml
  when: use_postgres and not update

- name: delete old directory
  file: path={{vmpool_path}} state=absent

- name: create dir for instances
  file: path={{vmpool_path}} state=directory mode=0755 owner={{deploy_user}} group={{deploy_user}} recurse=yes

- name: git checkout repo
  git: repo=https://github.com/2gis/vmmaster.git dest={{vmpool_path}} version={{vmmaster_version}}
  sudo: no

- name: install dependencies
  shell: chmod +x {{vmpool_path}}/install-dependencies.sh && {{vmpool_path}}/install-dependencies.sh

- name: install tox
  pip: name=tox
  sudo: yes

- name: create virtualenv with deps
  shell: "cd {{vmpool_path}} && tox"
  sudo: no

- name: apply special config.py in vmpool directory
  template: src={{vmpool_config_name}} dest={{vmpool_path}}/config.py mode=0644
  when: vmpool_config_name != "" and change_vmpool_config

- name: vmpool initialize
  shell: "cd {{vmpool_path}} && .tox/bin/python manage.py init"

- name: create log dir for instances
  file: path={{vmpool_path}}/logs state=directory mode=0755 owner={{deploy_user}} group={{deploy_user}} recurse=yes

- name: vmpool run migrations
  shell: "cd {{vmpool_path}} && .tox/bin/python manage.py migrations"
  sudo: yes
  when: not update

- name: change permitions for files
  file: path={{vmpool_path}} state=directory mode=0755 owner=vmmaster group=libvirtd recurse=yes

- name: install upstart vmpool script
  template: src=upstart_vmpool.conf dest=/etc/init/{{vmpool_name}}.conf mode=0644

- name: start vmpool service
  service: name={{vmpool_name}} state=started
  failed_when: "vmpool_status | failed and 'service not found' not in vmpool_status.msg"
  register: vmpool_status