# Nginx handlers file
---
  - name: restart nginx
    sudo: yes
    service: name=nginx state={{ item }} pattern=nginx enabled=yes
    with_items:
      - restarted
      - running

  - name: reload nginx
    sudo: yes
    service: name=nginx state={{ item }} pattern=nginx
    with_items:
      - reloaded
      - running
