# -*- coding: utf-8 -*-
SESSION_CLOSE_REASON_API_CALL = "Session closed via API stop_session call"
GET_ENDPOINT_ATTEMPTS = 10
ENDPOINT_REBUILD_ATTEMPTS = 3
REQUEST_TIMEOUT = 60
MAKE_REQUEST_ATTEMPTS_AMOUNT = 3
REQUEST_SLEEP_BASE_TIME = 5

ANY = u'ANY'
GET_SESSION_SLEEP_TIME = 2

# EndpointRemover #
ER_SLEEP_TIME = 2

# EndpointPreparer #
EP_SLEEP_TIME = 2
