# -*- coding: utf-8 -*-
SESSION_CLOSE_REASON_API_CALL = "Session closed via API stop_session call"
GET_ENDPOINT_ATTEMPTS = 10
GET_ENDPOINT_WAIT_TIME_INCREMENT = 5
ENDPOINT_REBUILD_ATTEMPTS = 3
REQUEST_TIMEOUT = 60
