# user for deploy on remote host
deploy_user: ansible

# home fir for vmmaster
vmmaster_path: /var/lib/vmmaster

# vmmaster version as commit or branch name
vmmaster_version: master

# install postgres and add config database path
use_postgres: true

# only update vmamster from repo
update: false

# postgres params
postgres_user: vmmaster
postgres_password: vmmaster
postgres_db: vmmaster_db
postgres_host: localhost

# config name from install_vmmaster/templates/
change_vmmaster_config: true
vmmaster_config_name: all

# config params from install_vmmaster/templates/
vmmaster_basedir: os.path.dirname(os.path.realpath(__file__))
vmmaster_port: 9000

vmmaster_clones_dir: "clones"
vmmaster_origins_dir: "origins"
vmmaster_session_dir: "session"

# screenshots
vmmaster_screenshots_dir: "screenshots"
vmmaster_screenshots_days: 7

# logging
vmmaster_log_dir: "log"
vmmaster_log_size: 5242880

# kvm
use_kvm: "True"
vmmaster_kvm_max_vm_count: 2
vmmaster_use_kvm_preloaded: false
vmmaster_kvm_preloaded:
  - {type: "ubuntu-14.04-x64", count: 1}

# openstack
use_openstack: "False"
vmmaster_openstack_max_vm_count: 2
vmmaster_use_openstack_preloaded: false
vmmaster_openstack_preloaded:
  - {type: "ubuntu-14.04-x64", count: 1}

openstack_auth_url: "localhost"
openstack_port: 5000
openstack_client_version: "v2.0"
openstack_username: "user"
openstack_password: "password"
openstack_tenant_name: "test"
openstack_tenant_id: "id"
openstack_zone_for_vm_create: ""
openstack_platform_name_prefix: "origin-"

vmmaster_vm_check: "False"
vmmaster_vm_check_frequency: 1800
vm_create_check_timeout: 5
vm_create_check_attempts: 1000
preloader_frequency: 3
vmmaster_session_timeout: 360
vmmaster_ping_timeout: 180

# additional logging
# sending logs into graylog2 or logstash (Graylog Extended Log Format, GELF)
vmmaster_graylog: ('logserver', 12201)

# graphite
vmmaster_graphite: ('graphite', 2003)

# selenium
vmmaster_selenium_port: 4455
vmmaster_agent_port: 9000

log_level: "INFO"
